# name: Deploy and Restart Nginx to Azure VM

---
# 1 Deploy nginx
- name: Deploy Nginx
  hosts: nginx
  become: true

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    # Run nginx
    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    # Restart nginx
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
