#  [nginx]
# web03 ansible_host=52.184.103.5
# web04 ansible_host=20.205.41.168

# [nginx:vars]
# ansible_user=devopsadmin
# ansible_python_interpreter=/usr/bin/python3

[nginx]
frontend-vm1 ansible_host=104.208.115.190
frontend-vm2 ansible_host=23.100.89.113

[nginx:vars]
ansible_user=YOUR_VM_USERNAME
ansible_password=YOUR_VM_PASSWORD
