[nginx]
frontend-vm1 ansible_host=104.208.115.190
frontend-vm2 ansible_host=23.100.89.113

[nginx:vars]
ansible_user=${{ secrets.AZURE_VM_USER }}
ansible_password=${{ secrets.AZURE_VM_PASSWORD }}
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
