 # Dynamic inventory
 [nginx_servers]
#web01 ansible_host=10.1.1.7
#web02 ansible_host=10.1.1.5
web03 ansible_host=52.184.103.5
#web04 ansible_host=10.1.1.6
web04 ansible_host=20.205.41.168

[nginx_servers:vars]
ansible_user=devopsadmin
ansible_python_interpreter=/usr/bin/python3
