# name: Deploy Nginx to Azure VM

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read    

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:

      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # 3 Get VM password from Azure Key Vault
      - name: Get VM Password from Key Vault
        uses: azure/cli@v2
        env:
          GH_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
        with:
          inlineScript: |
            # Check if password exists in GitHub Secrets
            if [ -n "$GH_VM_PASSWORD" ]; then
              echo "Password found in GitHub Secrets."
              VM_PASSWORD="$GH_VM_PASSWORD"
            else
              echo "Password not found in GitHub Secrets. Fetching from Key Vault..."

              VM_PASSWORD=$(az keyvault secret show \
                --vault-name "kp2026" \
                --name "vm-password" \
                --query value \
                --output tsv)

              if [ -z "$VM_PASSWORD" ]; then
                echo "ERROR: Failed to retrieve password from Key Vault."
                exit 1
              fi
            fi

              echo "::add-mask::$VM_PASSWORD"
              echo "VM_PASSWORD=$VM_PASSWORD" >> "$GITHUB_ENV"

      # 4. Install Ansible temporarily
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          python -m pip install --upgrade pip
          pip install ansible


      # 5. Get Azure VM Public IP
      - name: Get VM IP
        id: vm1
        run: |

          VM_IP=$(az vm show \
            --show-details \
            --resource-group "kp2" \
            --name "frontend-vm1" \
            --query publicIps \
            --output tsv)

          echo "VM IP: $VM_IP"

          echo "ip=$VM_IP" >> "$GITHUB_OUTPUT"


    # 6. Get Azure VM Public IP
      - name: Get VM IP
        id: vm2
        run: |

          VM_IP=$(az vm show \
            --show-details \
            --resource-group "kp2" \
            --name "frontend-vm2" \
            --query publicIps \
            --output tsv)

          echo "VM IP: $VM_IP"

          echo "ip=$VM_IP" >> "$GITHUB_OUTPUT"


      

    # 7. Create dynamic Ansible inventory
      - name: Create Inventory
        env:
          VM1_IP: ${{ steps.vm1.outputs.ip }}
          VM2_IP: ${{ steps.vm2.outputs.ip }}
          VM_USER: ${{ secrets.AZURE_VM_USER }}
          VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          mkdir -p inventory/dev
          cat > inventory/dev/hosts.ini <<EOF
          [nginx]
          frontend-vm1 ansible_host=${VM1_IP}
          frontend-vm2 ansible_host=${VM2_IP}

          [nginx:vars]
          ansible_user=${VM_USER}
          ansible_password=${VM_PASSWORD}
          ansible_connection=ssh
          ansible_ssh_common_args='-o StrictHostKeyChecking=no'
          EOF

          echo "Ansible inventory created."

    # 8. Ansible Ad-hoc Ping
      - name: Run Ansible Ad-hoc Ping
        run: |
           ANSIBLE_HOST_KEY_CHECKING=False ansible nginx -i inventory/dev/hosts.ini -m ping


    # 9. Deploy Nginx
      - name: Deploy Nginx
        run: |
          ansible-playbook \
            -i inventory/dev/hosts.ini \
            playbook/nginx.yml
