name: Deploy Nginx to Azure VM

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read    

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:

      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Install Ansible temporarily
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # 4. Get Azure VM Public IP
      - name: Get VM IP
        id: vm
        run: |

          VM_IP=$(az vm show \
            --show-details \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --name "${{ secrets.AZURE_VM_NAME }}" \
            --query publicIps \
            --output tsv)

          echo "VM IP: $VM_IP"

          echo "ip=$VM_IP" >> "$GITHUB_OUTPUT"

      # 5. Create dynamic Ansible inventory
      - name: Create Inventory
        run: |

          cat > inventory/prod/hosts.ini <<EOF

          [nginx]
          nginx-vm ansible_host=${{ steps.vm.outputs.ip }}

          [nginx:vars]
          ansible_user=${{ secrets.AZURE_VM_USER }}
          ansible_ssh_private_key_file=~/.ssh/azure_vm_key

          EOF

          cat inventory/prod/hosts.ini

      # 6. Configure SSH
      - name: Configure SSH
        run: |

          mkdir -p ~/.ssh

          echo "${{ secrets.AZURE_VM_SSH_KEY }}" \
            > ~/.ssh/azure_vm_key

          chmod 600 ~/.ssh/azure_vm_key

      # 7. Test connection
      - name: Ansible Ping
        run: |
          ansible nginx \
            -i inventory/prod/hosts.ini \
            -m ping

      # 8. Deploy Nginx
      - name: Deploy Nginx
        run: |
          ansible-playbook \
            -i inventory/prod/hosts.ini \
            playbooks/nginx.yml
